//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3615
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.3615.
// 
#pragma warning disable 1591

namespace Modeling.MamlayBackOfficeFront {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="FrontOfficeBinding", Namespace="http://backoffice.mamlay.ru/frontoffice")]
    public partial class FrontOfficeService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback newOrderOperationCompleted;
        
        private System.Threading.SendOrPostCallback confirmOrderOperationCompleted;
        
        private System.Threading.SendOrPostCallback changeOrderOperationCompleted;
        
        private System.Threading.SendOrPostCallback confirmChangeOperationCompleted;
        
        private System.Threading.SendOrPostCallback cancelOrderOperationCompleted;
        
        private System.Threading.SendOrPostCallback getOrderStatusOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public FrontOfficeService() {
            this.Url = global::Modeling.Properties.Settings.Default.Modeling_MamlayBackOfficeFront_FrontOfficeService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event newOrderCompletedEventHandler newOrderCompleted;
        
        /// <remarks/>
        public event confirmOrderCompletedEventHandler confirmOrderCompleted;
        
        /// <remarks/>
        public event changeOrderCompletedEventHandler changeOrderCompleted;
        
        /// <remarks/>
        public event confirmChangeCompletedEventHandler confirmChangeCompleted;
        
        /// <remarks/>
        public event cancelOrderCompletedEventHandler cancelOrderCompleted;
        
        /// <remarks/>
        public event getOrderStatusCompletedEventHandler getOrderStatusCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://backoffice.mamlay.ru/frontoffice#newOrder", RequestNamespace="http://backoffice.mamlay.ru/frontoffice", ResponseNamespace="http://backoffice.mamlay.ru/frontoffice")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public object newOrder(string date, string customer, int product1count, int product2count, int product3count) {
            object[] results = this.Invoke("newOrder", new object[] {
                        date,
                        customer,
                        product1count,
                        product2count,
                        product3count});
            return ((object)(results[0]));
        }
        
        /// <remarks/>
        public void newOrderAsync(string date, string customer, int product1count, int product2count, int product3count) {
            this.newOrderAsync(date, customer, product1count, product2count, product3count, null);
        }
        
        /// <remarks/>
        public void newOrderAsync(string date, string customer, int product1count, int product2count, int product3count, object userState) {
            if ((this.newOrderOperationCompleted == null)) {
                this.newOrderOperationCompleted = new System.Threading.SendOrPostCallback(this.OnnewOrderOperationCompleted);
            }
            this.InvokeAsync("newOrder", new object[] {
                        date,
                        customer,
                        product1count,
                        product2count,
                        product3count}, this.newOrderOperationCompleted, userState);
        }
        
        private void OnnewOrderOperationCompleted(object arg) {
            if ((this.newOrderCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.newOrderCompleted(this, new newOrderCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://backoffice.mamlay.ru/frontoffice#confirmOrder", RequestNamespace="http://backoffice.mamlay.ru/frontoffice", ResponseNamespace="http://backoffice.mamlay.ru/frontoffice")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public bool confirmOrder(string date, int orderId, int orderType) {
            object[] results = this.Invoke("confirmOrder", new object[] {
                        date,
                        orderId,
                        orderType});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void confirmOrderAsync(string date, int orderId, int orderType) {
            this.confirmOrderAsync(date, orderId, orderType, null);
        }
        
        /// <remarks/>
        public void confirmOrderAsync(string date, int orderId, int orderType, object userState) {
            if ((this.confirmOrderOperationCompleted == null)) {
                this.confirmOrderOperationCompleted = new System.Threading.SendOrPostCallback(this.OnconfirmOrderOperationCompleted);
            }
            this.InvokeAsync("confirmOrder", new object[] {
                        date,
                        orderId,
                        orderType}, this.confirmOrderOperationCompleted, userState);
        }
        
        private void OnconfirmOrderOperationCompleted(object arg) {
            if ((this.confirmOrderCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.confirmOrderCompleted(this, new confirmOrderCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://backoffice.mamlay.ru/frontoffice#changeOrder", RequestNamespace="http://backoffice.mamlay.ru/frontoffice", ResponseNamespace="http://backoffice.mamlay.ru/frontoffice")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string changeOrder(string date, int orderId, object products) {
            object[] results = this.Invoke("changeOrder", new object[] {
                        date,
                        orderId,
                        products});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void changeOrderAsync(string date, int orderId, object products) {
            this.changeOrderAsync(date, orderId, products, null);
        }
        
        /// <remarks/>
        public void changeOrderAsync(string date, int orderId, object products, object userState) {
            if ((this.changeOrderOperationCompleted == null)) {
                this.changeOrderOperationCompleted = new System.Threading.SendOrPostCallback(this.OnchangeOrderOperationCompleted);
            }
            this.InvokeAsync("changeOrder", new object[] {
                        date,
                        orderId,
                        products}, this.changeOrderOperationCompleted, userState);
        }
        
        private void OnchangeOrderOperationCompleted(object arg) {
            if ((this.changeOrderCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.changeOrderCompleted(this, new changeOrderCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://backoffice.mamlay.ru/frontoffice#confirmChange", RequestNamespace="http://backoffice.mamlay.ru/frontoffice", ResponseNamespace="http://backoffice.mamlay.ru/frontoffice")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public bool confirmChange(string date, int orderId, object products) {
            object[] results = this.Invoke("confirmChange", new object[] {
                        date,
                        orderId,
                        products});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void confirmChangeAsync(string date, int orderId, object products) {
            this.confirmChangeAsync(date, orderId, products, null);
        }
        
        /// <remarks/>
        public void confirmChangeAsync(string date, int orderId, object products, object userState) {
            if ((this.confirmChangeOperationCompleted == null)) {
                this.confirmChangeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnconfirmChangeOperationCompleted);
            }
            this.InvokeAsync("confirmChange", new object[] {
                        date,
                        orderId,
                        products}, this.confirmChangeOperationCompleted, userState);
        }
        
        private void OnconfirmChangeOperationCompleted(object arg) {
            if ((this.confirmChangeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.confirmChangeCompleted(this, new confirmChangeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://backoffice.mamlay.ru/frontoffice#cancelOrder", RequestNamespace="http://backoffice.mamlay.ru/frontoffice", ResponseNamespace="http://backoffice.mamlay.ru/frontoffice")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public bool cancelOrder(string date, int orderId) {
            object[] results = this.Invoke("cancelOrder", new object[] {
                        date,
                        orderId});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void cancelOrderAsync(string date, int orderId) {
            this.cancelOrderAsync(date, orderId, null);
        }
        
        /// <remarks/>
        public void cancelOrderAsync(string date, int orderId, object userState) {
            if ((this.cancelOrderOperationCompleted == null)) {
                this.cancelOrderOperationCompleted = new System.Threading.SendOrPostCallback(this.OncancelOrderOperationCompleted);
            }
            this.InvokeAsync("cancelOrder", new object[] {
                        date,
                        orderId}, this.cancelOrderOperationCompleted, userState);
        }
        
        private void OncancelOrderOperationCompleted(object arg) {
            if ((this.cancelOrderCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.cancelOrderCompleted(this, new cancelOrderCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://backoffice.mamlay.ru/frontoffice#getOrderStatus", RequestNamespace="http://backoffice.mamlay.ru/frontoffice", ResponseNamespace="http://backoffice.mamlay.ru/frontoffice")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public object getOrderStatus(string date, int orderId) {
            object[] results = this.Invoke("getOrderStatus", new object[] {
                        date,
                        orderId});
            return ((object)(results[0]));
        }
        
        /// <remarks/>
        public void getOrderStatusAsync(string date, int orderId) {
            this.getOrderStatusAsync(date, orderId, null);
        }
        
        /// <remarks/>
        public void getOrderStatusAsync(string date, int orderId, object userState) {
            if ((this.getOrderStatusOperationCompleted == null)) {
                this.getOrderStatusOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetOrderStatusOperationCompleted);
            }
            this.InvokeAsync("getOrderStatus", new object[] {
                        date,
                        orderId}, this.getOrderStatusOperationCompleted, userState);
        }
        
        private void OngetOrderStatusOperationCompleted(object arg) {
            if ((this.getOrderStatusCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getOrderStatusCompleted(this, new getOrderStatusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void newOrderCompletedEventHandler(object sender, newOrderCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class newOrderCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal newOrderCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public object Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((object)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void confirmOrderCompletedEventHandler(object sender, confirmOrderCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class confirmOrderCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal confirmOrderCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void changeOrderCompletedEventHandler(object sender, changeOrderCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class changeOrderCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal changeOrderCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void confirmChangeCompletedEventHandler(object sender, confirmChangeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class confirmChangeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal confirmChangeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void cancelOrderCompletedEventHandler(object sender, cancelOrderCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class cancelOrderCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal cancelOrderCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void getOrderStatusCompletedEventHandler(object sender, getOrderStatusCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getOrderStatusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getOrderStatusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public object Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((object)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591