//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3615
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.3615.
// 
#pragma warning disable 1591

namespace Modeling.BackOfficeSim {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SimulationBinding", Namespace="http://corporateis/simulation")]
    public partial class SimulationService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback niceStartOperationCompleted;
        
        private System.Threading.SendOrPostCallback getShoppingListOperationCompleted;
        
        private System.Threading.SendOrPostCallback receivingMaterialsOperationCompleted;
        
        private System.Threading.SendOrPostCallback getDayPlanOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public SimulationService() {
            this.Url = global::Modeling.Properties.Settings.Default.Modeling_BackOfficeSim_SimulationService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event niceStartCompletedEventHandler niceStartCompleted;
        
        /// <remarks/>
        public event getShoppingListCompletedEventHandler getShoppingListCompleted;
        
        /// <remarks/>
        public event receivingMaterialsCompletedEventHandler receivingMaterialsCompleted;
        
        /// <remarks/>
        public event getDayPlanCompletedEventHandler getDayPlanCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://corporateis/simulation#niceStart", RequestNamespace="http://corporateis/simulation", ResponseNamespace="http://corporateis/simulation")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public bool niceStart(string date) {
            object[] results = this.Invoke("niceStart", new object[] {
                        date});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void niceStartAsync(string date) {
            this.niceStartAsync(date, null);
        }
        
        /// <remarks/>
        public void niceStartAsync(string date, object userState) {
            if ((this.niceStartOperationCompleted == null)) {
                this.niceStartOperationCompleted = new System.Threading.SendOrPostCallback(this.OnniceStartOperationCompleted);
            }
            this.InvokeAsync("niceStart", new object[] {
                        date}, this.niceStartOperationCompleted, userState);
        }
        
        private void OnniceStartOperationCompleted(object arg) {
            if ((this.niceStartCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.niceStartCompleted(this, new niceStartCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://corporateis/simulation#getShoppingList", RequestNamespace="http://corporateis/simulation", ResponseNamespace="http://corporateis/simulation")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public object getShoppingList(string date) {
            object[] results = this.Invoke("getShoppingList", new object[] {
                        date});
            return ((object)(results[0]));
        }
        
        /// <remarks/>
        public void getShoppingListAsync(string date) {
            this.getShoppingListAsync(date, null);
        }
        
        /// <remarks/>
        public void getShoppingListAsync(string date, object userState) {
            if ((this.getShoppingListOperationCompleted == null)) {
                this.getShoppingListOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetShoppingListOperationCompleted);
            }
            this.InvokeAsync("getShoppingList", new object[] {
                        date}, this.getShoppingListOperationCompleted, userState);
        }
        
        private void OngetShoppingListOperationCompleted(object arg) {
            if ((this.getShoppingListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getShoppingListCompleted(this, new getShoppingListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://corporateis/simulation#receivingMaterials", RequestNamespace="http://corporateis/simulation", ResponseNamespace="http://corporateis/simulation")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public bool receivingMaterials(string date, int deliveryId, object materials) {
            object[] results = this.Invoke("receivingMaterials", new object[] {
                        date,
                        deliveryId,
                        materials});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void receivingMaterialsAsync(string date, int deliveryId, object materials) {
            this.receivingMaterialsAsync(date, deliveryId, materials, null);
        }
        
        /// <remarks/>
        public void receivingMaterialsAsync(string date, int deliveryId, object materials, object userState) {
            if ((this.receivingMaterialsOperationCompleted == null)) {
                this.receivingMaterialsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnreceivingMaterialsOperationCompleted);
            }
            this.InvokeAsync("receivingMaterials", new object[] {
                        date,
                        deliveryId,
                        materials}, this.receivingMaterialsOperationCompleted, userState);
        }
        
        private void OnreceivingMaterialsOperationCompleted(object arg) {
            if ((this.receivingMaterialsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.receivingMaterialsCompleted(this, new receivingMaterialsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://corporateis/simulation#getDayPlan", RequestNamespace="http://corporateis/simulation", ResponseNamespace="http://corporateis/simulation")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public object getDayPlan(string date) {
            object[] results = this.Invoke("getDayPlan", new object[] {
                        date});
            return ((object)(results[0]));
        }
        
        /// <remarks/>
        public void getDayPlanAsync(string date) {
            this.getDayPlanAsync(date, null);
        }
        
        /// <remarks/>
        public void getDayPlanAsync(string date, object userState) {
            if ((this.getDayPlanOperationCompleted == null)) {
                this.getDayPlanOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetDayPlanOperationCompleted);
            }
            this.InvokeAsync("getDayPlan", new object[] {
                        date}, this.getDayPlanOperationCompleted, userState);
        }
        
        private void OngetDayPlanOperationCompleted(object arg) {
            if ((this.getDayPlanCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getDayPlanCompleted(this, new getDayPlanCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void niceStartCompletedEventHandler(object sender, niceStartCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class niceStartCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal niceStartCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void getShoppingListCompletedEventHandler(object sender, getShoppingListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getShoppingListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getShoppingListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public object Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((object)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void receivingMaterialsCompletedEventHandler(object sender, receivingMaterialsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class receivingMaterialsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal receivingMaterialsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void getDayPlanCompletedEventHandler(object sender, getDayPlanCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getDayPlanCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getDayPlanCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public object Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((object)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591